### ISSUE TITLE
Suggestion for adding new data fields to the model

### ISSUE THREAD

**Issue by mrbm** [sigurdga/django-jquery-file-upload#16]
I was messing around with you app, its great. However I am having a little difficulty adding new fields, specifically datetime fields and url fields. I thought it would be good if there was a timestamp of some sort upon uploading the picture, however json seems to be having issues with the datatime field and the url field...suggestions?

**Comment by sigurdga** [comment]
Sorry I couldn't help these years ago. I tested adding a new field now, and it worked. Maybe because of upgrades to newer Django, or other fixes.
