### ISSUE TITLE
list of files not dont show

### ISSUE THREAD

**Issue by Arthedian** [sigurdga/django-jquery-file-upload#51]
When i tried add this to my page with bootstrap 3.0.0 and the files list (already uploaded and not uploaded) are not showing, but are in code. Like in here: https://www.dropbox.com/s/fgtpspazm5orl3r/Screenshot%202014-02-11%2016.54.43.png

**Comment by sigurdga** [comment]
I haven't seen this. And it is fairly old now, so I'm closing it. Sorry that I couldn't help out.
