### ISSUE TITLE
Required field... how?

### ISSUE THREAD

**Issue by santocch** [sigurdga/django-jquery-file-upload#52]
Hello,
I have a problem with required field... I downloaded the application and everything was fine... then I tried to add in models.py a simple required field like this 

    test = models.CharField(max_length=60,)

First attempt gave me, as expected because I didn't try to give to the new field some value, this error:

    {"test": ["This field is required."]}

Second attempt I added a line to the save method in models.py (replicating what is done for the slug field) 

    def save(self, *args, **kwargs):
        ...
        self.test = 'foo'

same error... Third attempt (after a LOT of googling) I changed views.py like this

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.test = "foo"
        self.object.save()
        ...

again the same error... I don't know now what to do... any suggestion? 

Thanks

**Comment by artyomboyko** [comment]
Same issue here :(

**Comment by sigurdga** [comment]
Closing this as it is nearly two years ago. I'm sorry I didn't get the chance to help back then. I was not doing any active Django work at the time.

If anybody else sees this, I think the answer here is to set `blank=True` if the field could be empty. Or we need to actually add the field to the form.
