### ISSUE TITLE
pictures uploaded but thumbnails error 404 file not found

### ISSUE THREAD

**Issue by sp8899** [sigurdga/django-jquery-file-upload#57]
The pictures are uploaded but there are 404 file not found errors for the thumbnails as screenshots attached. I am pretty new to django, can someone please help. Thanks.
![image](https://cloud.githubusercontent.com/assets/10415895/5990729/ef228402-a9fa-11e4-84f5-5e395c2e7e6f.png)

**Comment by sigurdga** [comment]
I guess it won't help you now, but the urls was not working until I made it compatible with Django 1.9 just now. I guess this problem was with at least 1.8 as well.

**Comment by JawnZ** [comment]
I'm still having this issue...

I got it to work on Django 2.0 other than this problem...is it just a missing line in the url.py to point to pictures folder?

**Comment by sigurdga** [comment]
Hi @JawnZ

Could you try a clean clone? Then
```sh
virtualenv -p python2 venv
source venv/bin/activate
pip install -r requirements.txt
./manage.py migrate
./manage.py runserver
```

Then try localhost:8000 and do your uploads again. In my case, after the clean clone as described, the files are downloaded nicely from /media/pictures. Still on Django 1.9 in that case. I will see how much work is needed to get to 2.0 now.

**Comment by sigurdga** [comment]
The code repository worked fine with 1.10.8 and 1.11.10, but developers should use Django 2 now.

I needed to change the url parts of the code and was able to migrate to Django 2.0 (and Python 3). You could try a clean checkout of the new version and see if it works for you:

```sh
virtualenv -p python3 venv
source venv/bin/activate
pip install -r requirements.txt
./manage.py migrate
./manage.py runserver
```

Please deactivate from the old virtualenv and delete it before creating the new. I hope this gets you in the right direction, @JawnZ
