### ISSUE TITLE
Django >1.6 Support

### ISSUE THREAD

**Issue by saifrahmed** [sigurdga/django-jquery-file-upload#58]
This requires Django<1.6, for which has passed end-of-life (see: https://www.djangoproject.com/download/)

It would be good to upgrade this to support Django 1.7 or ideally 1.8 since that is an LTS version.  I'd be happy to help with this upgrade.

**Comment by sigurdga** [comment]
Thank you for your interest in this project. I haven't had much time to work with Django lately, so I would be happy to get any help. I'm not sure when I will have time to look at this, so if you send any PRs, that would speed things up (as I would need to look at the details).

The goal should be to support 1.8

Oh, now I see from the forks page that there are several attempts already.

**Comment by rootux** [comment]
probably can close this issue. looking at https://github.com/sigurdga/django-jquery-file-upload/commit/9957fcc02907d81aea1aaa4f6a043278b1c9411d I understand project now support 1.8.
can you confirm?

**Comment by sigurdga** [comment]
Yes. Pull request #59 closes the issue.
