### ISSUE TITLE
How to add support for audio files?

### ISSUE THREAD

**Issue by indrajithi** [sigurdga/django-jquery-file-upload#65]

**Comment by sigurdga** [comment]
Hi @indrajithi 

There are some restrictions in the javascript library used ([jquery-file-upload](http://aquantum-demo.appspot.com/file-upload)). If you [search for "png"](https://github.com/sigurdga/django-jquery-file-upload/search?utf8=%E2%9C%93&q=png&type=), you should see where. Just add the allowed mimetypes where the library are restricting mimetypes (`acceptFileTypes`).

The Python/Django code should be allowing these files already.
