### ISSUE TITLE
no pagenation,better to  move the upload file area  to top div 

### ISSUE THREAD

**Issue by b2scrip** [sigurdga/django-jquery-file-upload#69]
image you have lots of images to upload . without pagenation is really painful.
you have to scroll your mouse to the bottom of the page .

**Comment by sigurdga** [comment]
Hi

Sorry for the very late reply.

The intention of this tool is to create a small working example, not a complete solution for production.

But if you add a small pull request that will improve this example, I will gladly pull it into the code base.
