### ISSUE TITLE
Django version in requirements does not match

### ISSUE THREAD

**Issue by Abrunacci** [sigurdga/django-jquery-file-upload#70]
The django application is built for django 1.9 but the requirements point to django 2.0 and some imports do not work. I solved it by uninstalling django and installing the correct version.

I thought it was right to let you know.

**Comment by Abrunacci** [comment]
I make you a pull request to fix this.
https://github.com/sigurdga/django-jquery-file-upload/pull/71

**Comment by sigurdga** [comment]
Thanks  @Abrunacci 

I hope I get the time to update the code to 2.0 soon.

**Comment by Abrunacci** [comment]
No problem. If I have some time i will glad to help. Just let me know

**Comment by sigurdga** [comment]
We are at Django 2.0 now :)
